-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'


-- This ensures applications know how to find services like the keyring





--exec-once = hyprpaper




-- Stores only text data


-- Stores only image data


-- Restore the last used theme on startup

-- exec-once = sh -c 'sh ~/.config/hypr/scripts/apply-theme.sh $(cat ~/.config/hypr/themes/current_theme.state)'






-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("sh ~/.config/hypr/scripts/launch_waybar.sh")
    hl.exec_cmd("dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY WAYLAND_DISPLAY")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("dunst")
    hl.exec_cmd("nm-applet --indicator")
    hl.exec_cmd("hyprsunset")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("sh ~/.config/hypr/scripts/battery_watcher.sh &")
    hl.exec_cmd("sh -c 'sh ~/.config/hypr/scripts/apply-theme.sh $(cat ~/.config/hypr/themes/current_theme.state) --boot'")
    hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
    hl.exec_cmd("echo \"Exec.conf was sourced at $(date)\" >>/tmp/exec_log.txt")
    hl.exec_cmd("hyprctl setcursor \"$(cat ~/.config/hypr/cursor.theme)\" 24")
    hl.exec_cmd("swww-daemon")
end)
