-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.workspace_rule({
    workspace = 1,
    name = "",
})

hl.workspace_rule({
    workspace = 2,
    name = "",
})

hl.workspace_rule({
    workspace = 3,
    name = "",
})

hl.workspace_rule({
    workspace = 4,
    name = "",
})

hl.workspace_rule({
    workspace = 5,
    name = "",
})
