# --- Configuration for the Anime Organizer ---

# The messy folder where your sources are.
DOWNLOADS_DIR="/mnt/REM/Atashi/Animiru"

# The clean folder where your organized library will be created.
LIBRARY_DIR="/mnt/REM/Atashi/Anime Active"
