# Kitty Configuration Template

# --- Font & Layout Settings ---
font_family JetBrainsMono Nerd Font
bold_font auto
italic_font auto
font_size 12

#background_opacity 0.4
window_padding_width 24
scrollback_lines 5000


# --- Color Scheme ---
# These values are injected by the theme-switcher script

foreground                      #4c4f69
background                      #eff1f5
selection_foreground            #eff1f5
selection_background            #acb0be
cursor                          #4c4f69
url_color                       #1e66f5

# Black
color0                          #bcc0ca
color8                          #9ca0b0

# Red
color1                          #d20f39
color9                          #d20f39

# Green
color2                          #40a02b
color10                         #40a02b

# Yellow
color3                          #df8e1d
color11                         #df8e1d

# Blue
color4                          #1e66f5
color12                         #1e66f5

# Magenta
color5                          #8839ef
color13                         #8839ef

# Cyan
color6                          #179299
color14                         #179299

# White
color7                          #7c7f93
color15                         #6c6f85
